# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: docker

provisioner:
  name: salt_solo
  formula: openscap
  state_top:
    base:
      "*":
        - openscap

platforms:
  - name: debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        openscap.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - openscap
