# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: openscap
  state_top:
    base:
      "*":
        - openscap
  pillars:
    top.sls:
      base:
        "*":
          - openscap

platforms:
  - name: bento/debian-8.8

suites:
  - name: default
    provisioner:
      pillars:
        openscap.sls:
          openscap:
            enabled: true

  - name: custom
    provisioner:
      pillars-from-files:
        openscap.sls: pillar-custom.sls
